apiVersion: apps/v1
kind: Deployment
metadata:
  name: tru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tru
  template:
    metadata:
      labels:
        app: tru
    spec:
      containers:
      - name: my-container
        image: nginx
        ports:
         - containerPort: 8080
        command: [ "bash", "-c", "echo 'Hello, World iam trupti kulkarnii' && sleep 3600" ]
