apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hi-world
  template:
    metadata:
      labels:
        app: hi-world
    spec:
      containers:
      - name: my-container
        image: nginx
        command: [ "bash", "-c", "echo 'Hello, World iam trupti k' && sleep 3600" ]
