apiVersion: apps/v1
kind: Deployment
metadata:
  name: truptikul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truptikul
  template:
    metadata:
      labels:
        app: truptikul
    spec:
      containers:
        - name: my-container
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          command: [ "bash", "-c", "echo 'Hello, my name is trupti' && nginx -g 'daemon off;'" ]
          
