apiVersion: apps/v1
kind: Deployment
metadata:
  name: trupti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trupti
  template:
    metadata:
      labels:
        app: trupti
    spec:
      containers:
      - name: my-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        command: [ "bash", "-c", "echo 'Hello, World iam trupti kulkarnii' && sleep 3600" ]
